--THIS IS NOT 100% SQL CODE. CHECK FOR SQLLITE 3 IF YOU WANT TO MAKE CHANGES
CREATE TABLE stock (
    'internal_id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'id' VARCHAR(16) NOT NULL,
    'name' VARCHAR(128) NOT NULL,
    'desc' VARCHAR(256) NOT NULL,
    'category' INT(8) NULL DEFAULT NULL);

CREATE TABLE category (
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'name' VARCHAR(128) NOT NULL,
    'desc' VARCHAR(256) NOT NULL,
    'category' INT(8) NULL DEFAULT NULL);

CREATE TABLE logs (
    'product_id' INT(8) NOT NULL,
    'log' TEXT NOT NULL);